version: '3.8'

services:
  web:
    build: .
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html  # ✅ This is fine if your local dir has index.php
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Aanthony92268@
      - MYSQL_DATABASE=finase

  db:
    image: mysql:8.0  # ✅ Use correct database image
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aanthony92268@
      MYSQL_DATABASE: finase
      MYSQL_USER: mark
      MYSQL_PASSWORD: markpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
